NormalSeed/UnityCooperationProject

- Assets/KDJ/Import.meta
- Assets/KDJ/script/Ball.cs
- Assets/KDJ/script/Ball.cs.meta
- Assets/KDJ/script/BallScript.cs
- Assets/KDJ/script/BallScript.cs.meta
> [FEAT]플레이어 방향전환

- Assets/YTW/Prefabs/Monster.prefab
- Assets/YTW/Scripts/AttackTrap.cs
- Assets/YTW/Scripts/OnDamaged.cs
- Assets/YTW/TestScene.unity
트랩 트리거진입시 작동안하는 오류 해결
hp가 0이되고 오브젝트풀로 반환되지 않는 오류 해결
오브젝트풀로 반환된후 다시 활성화 될때 데미지 입는 로직을 해결
> [Fix] 트랩 오류 해결

- Assets/KDJ/Bounce.physicMaterial
- Assets/KDJ/Bounce.physicMaterial.meta
- Assets/KDJ/script/Ball.cs
- Assets/KDJ/script/PlayerAnimator.cs
- Assets/KDJ/script/PlayerAnimator.cs.meta
- Assets/KDJ/script/PlayerHealth.cs
- Assets/KDJ/script/PlayerHealth.cs.meta
공이 몬스터에 닿으면 체력 감소, 0이면 Game Over
추가적으로 플레이어 공이 가는 방향으로 회전하고 기존 점프 상하좌우에서 착지기능 구현하고 나중에 회피구현도 넣을예정
> [FEAT]플레이어 체력및착지기능 구현

- Assets/LHJ/Prefabs/SpeedItem.prefab
- Assets/LHJ/Scripts/AttackItem.cs
- Assets/LHJ/Scripts/PotionItem.cs
- Assets/LHJ/Scripts/ScoreItem.cs
- Assets/LHJ/Scripts/SpeedItem.cs
- Assets/LHJ/Scripts/TestBuffText.cs
- Assets/LHJ/Scripts/TestBuffText.cs.meta
- Assets/LHJ/TestScene.unity
SpeedItem및 Item을 먹으면 이펙트가 형성되게 하도록 설정하였습니다.
현재 Test를 할 때는  Consoll창에 Debug.Log로 플레이어의 공격력이나 이동속도등 상태를 나타내는데
왼쪽 상단에 UI를 하나 만들어서 아이템을 먹었을때 별로 어떤 변화가 나타나는지 확인 할 수 있게 할 생각입니다.
현재 UI는 거의 Test용으로 틀만 갖춰진 상태이고 이후 작업에서 설정하려고 합니다.
> [Feat] Item 이펙트 기능 및 UI 초기구성

- Assets/LHJ/Scripts/AttackItem.cs
- Assets/LHJ/Scripts/PotionItem.cs
- Assets/LHJ/Scripts/ScoreItem.cs
- Assets/LHJ/Scripts/SpeedItem.cs
- Assets/LHJ/Scripts/TestBuffText.cs
- Assets/LHJ/Scripts/Testplayercontroll.cs
- Assets/LHJ/TestScene.unity
Player가 Item을 먹게 되면 Debug.log가 아닌 왼쪽 상단에 구성된 panel안에서 아이템 효과에 알맞는 Text가 나오도록 구현
> [Feat] UI 구현

- Assets/LKH/Scripts/TrapScripts/SpringPad.cs
> [Fix] 디버그 메세지 삭제

- Assets/KDJ/script/BallPlay.cs
- Assets/KDJ/script/BallPlay.cs.meta
- Assets/KDJ/script/GM.cs
- Assets/KDJ/script/GM.cs.meta
- Assets/KDJ/script/GravityController.cs
- Assets/KDJ/script/GravityController.cs.meta
> [FEAT]플레이어 속도 초기설정및 방향설정

- Assets/LKH/Materials/AntLionTrapTest.mat
- Assets/LKH/Materials/AntLionTrapTest.mat.meta
- Assets/LKH/Scripts/TrapScripts/AntLionTrap.cs
- Assets/LKH/Scripts/TrapScripts/AntLionTrap.cs.meta
> [Feat] 개미지옥 트랩 추가

- Assets/KDJ/Script/CameraController.cs
- Assets/KDJ/Script/PB.cs
- Assets/KDJ/Script/Player.cs
- Assets/KDJ/script/Ball.cs
- Assets/KDJ/script/BallPlay.cs
- Assets/KDJ/script/CameraController.cs
- Assets/KDJ/script/GravityController.cs
- Assets/KDJ/script/PB.cs
- Assets/KDJ/script/PlayerAnimator.cs
- Assets/KDJ/script/PlayerHealth.cs
- Assets/KDJ/script/player.cs
CameraControll.cs: 이 스크립트는 카메라가 특정 게임 오브젝트를 따라가도록 할 때 사용하는 카메라 추적 스크립트
카메라가 플레이어 공을 추적하는 코드
Player.cs: 이 스크립트 는 상하좌우 방향을 기본방향 움직이는 코드
PB.cs: 이 스크립트는 이 이동하고, 점프하며, 아이템을 먹고, 목표 지점에 도달하면 다음 스테이지로 이동하는 구조에서 사용
플레이어가 공을 굴리며 장애물을 피하고 아이템을 전부 수집해서 목표 지점에 도착해야 클리어
BallPlay.cs: 이 스크립트는 공의 초기 움직임을 설정 게임이 시작될 때 공의 속도와 방향을 설정하고,BallPlay클래스가 전체 게임에서 하나만 존재하도록 관리하는 역할
Ball.cs:이 스크립트는 Unity에서 공이 벽이나 플레이어에 닿으면 튕기듯이 방향을 바꾸며 계속 움직이는 기능을 구현할 때 사용하는 스크립트
자동으로 움직이고 벽에 부딪히면 방향을 반사하는 공을 만들고 싶을 때 사용
PlayerHealth.cs: 이 스크립트는 플레이어의 최대 체력을 설정,몬스터나 장애물과 충돌 시 데미지를 입히고 싶은 게임에서 사용
공을 굴려 몬스터를 피해야 하는 게임에서, 몬스터에 닿으면 체력 감소
PlayerAnimator.cs:이 스크립트는 플레이어 캐릭터의 애니메이션과 움직임을 함께 제어하는 스크립트
키 입력에 따라 공이 아닌 몬스터나 사람일경우 걷고, 달리고, 점프하고, 방향 전환기능
> [FEAT]플레이어 스크립트 최종정리

- Assets/LHJ/Prefabs/ItemTextPanel.prefab
- Assets/LHJ/Prefabs/ItemTextPanel.prefab.meta
> [Fix] Item Text프리팹화

- Assets/LKH/Scenes.meta
- Assets/LKH/Scenes/Bouncing.unity
- Assets/LKH/Scenes/Bouncing.unity.meta
- ProjectSettings/EditorBuildSettings.asset
> [Feat] 신규 스테이지 작성

- Assets/LHJ/Scripts/PlayerStats.cs
> [Fix] score 추가수정

- Assets/KMS/PREFABS/StageClearUI.prefab
- Assets/KMS/SCENES/Stage1Scene.unity
- Assets/KMS/SCENES/TitleScene.unity
- Assets/KMS/SCRIPTS/StageClearUI.cs
- Assets/KMS/SCRIPTS/StageManager.cs
- ProjectSettings/EditorBuildSettings.asset
스테이지 클리어 시 스테이지의 이름이 뜨도록 하였습니다.
마지막 스테이지 클리어 시 타이틀로 돌아가는 기능을 추가하였습니다.
> [Feat] 스테이지클리어UI 기능개선

- Assets/LKH/Prefabs/AccelerationPlane.prefab
- Assets/LKH/Prefabs/AccelerationPlane.prefab.meta
- Assets/LKH/Prefabs/BouncinWall.prefab
- Assets/LKH/Prefabs/BouncinWall.prefab.meta
- Assets/LKH/Prefabs/DecelerationPlane.prefab
- Assets/LKH/Prefabs/DecelerationPlane.prefab.meta
- Assets/LKH/Prefabs/SpringPad.prefab
- Assets/LKH/Prefabs/SpringPad.prefab.meta
> [Feat] 트랩 프리팹 생성

- Assets/KDJ/Prefab3.meta
- Assets/KDJ/Prefab3/Player.prefab.meta
- Assets/LKH/Scenes/Bouncing.unity
- Assets/LKH/Scripts/Shooter.cs
공이 굴러감에 따라 총알 생성 위치가 달라지는 문제 수정
> [Fix] MergePoint 로직 수정

- Assets/LKH/Prefabs/Player.prefab
- Assets/LKH/Scenes/Bouncing.unity
실수로 develope에 커밋해서 브랜치 옮겨 다시 작업함
Bouncing 스테이지의 모든 벽을 튕기는 벽 트랩으로 설정
> Reapply "[Feat] Bouncing 스테이지 트랩 추가"

- Assets/LKH/Prefabs/AccelerationPlane.prefab
- Assets/LKH/Prefabs/Player.prefab
- Assets/LKH/Scenes/Bouncing.unity
- Assets/LKH/Scripts/TrapScripts/AccelerationPlaneTest.cs
> [Fix] 가속 바닥 로직 수정

- Assets/YTW/Scripts/PlayerBullet.cs
- Assets/YTW/Scripts/PlayerBullet.cs.meta
- Assets/YTW/Scripts/RangedAttack.cs
플레이어 전용 불렛 스크립트 추가
총알 사운드 생성후 제거
> [Feat] 플레이어 불렛 스크립트 추가

- Assets/KMS/SCENES/Stage1Scene.unity
- Assets/KMS/SCENES/Stage2Scene.unity
- Assets/KMS/SCRIPTS/InfoUI.cs
스테이지에 구성을 일부 변경하였습니다.
화면 정보 UI 표기상 오류를 한가지 수정하였습니다.
> [Fix] 스테이지 구성 수정

- Assets/LKH/Prefabs/Player.prefab
- Assets/LKH/Prefabs/PlayerBullet.prefab
- Assets/LKH/Scenes/Bouncing.unity
- Assets/LKH/Scripts/MonsterSpawner.cs
- ProjectSettings/EditorBuildSettings.asset
플레이어 체력, 속도 조절
BouncingMaze 스테이지 난이도 조절
> [Fix] 플레이어 및 스테이지 난이도 조정

- Assets/LKH/Prefabs/Player.prefab
- Assets/LKH/Scenes/Bouncing.unity
- Assets/LKH/Scripts/Shooter.cs
- ProjectSettings/InputManager.asset
> [Fix] 플레이어 최종수정, 키 배정 수정

- Assets/LHJ/StageScene.unity
> [Fix] Scene난이도 조정

- Assets/KMS/HealthbarPos.cs
- Assets/KMS/HealthbarPos.cs.meta
- Assets/KMS/PREFABS/InfoUI.prefab
- Assets/KMS/SCENES/Stage1Scene.unity
- Assets/KMS/SCENES/Stage2Scene.unity
UI에 체력을 표시하는 대신, ondamaged 스크립트가 체력바 오브젝트를 인식하도록 하였습니다.
체력바가 플레이어를 따라 돌아가는것을 스크립트를 추가하여 방지했습니다.
> Fix] 플레이어 체력바 수정

- Assets/LKH/Scenes/Bouncing.unity
- Assets/LKH/Scripts/HealthBarPos2.cs
- Assets/LKH/Scripts/HealthBarPos2.cs.meta
플레이어 체력바가 움직임에 따라 흔들리고 깜박거리는 현상 수정
> [Feat] 플레이어 체력바 흔들림 수정

- Assets/LKH/Scenes/Bouncing.unity
> [Fix] 체력바 표시 수정

- Assets/LKH/Scenes/Bouncing.unity
- Assets/LKH/Scripts/Shooter.cs
공격력 아이템을 획득했을 때 정상적으로 가하는 데미지가 늘어나도록 로직 수정
> [Fix] 슈터 로직 수정

- Assets/YTW/Materials/Red_X.mat
- Assets/YTW/Materials/Red_X.mat.meta
- Assets/YTW/Scenes/GameScene.unity
- Assets/YTW/Scripts/HealthBar.cs
- Assets/YTW/Scripts/PlayerBullet.cs
총알의 데미지가 플레이어의 공격력에 따라 변화
체력바를 프레임마다 호출에서 Update마다 호출로 변경
> [Fix] 총알 데미지 수정, 체력바 기능 수정

- Assets/LKH/Scenes/Bouncing.unity
Bouncing 스테이지 내 Attack 아이템 버프시간 10초로 증가
> [Fix] Bouncing 스테이지 수정

- Assets/LKH/Prefabs/Player.prefab
> [Fix] 플레이어 프리팹 수정

- Assets/YTW/Scenes/GameScene.unity
- Assets/YTW/Scripts/OnDamaged.cs
> [Fix] 체력바 수정

- Assets/LHJ/Prefabs/ScoreItem.prefab
- Assets/LHJ/StageScene.unity
Scene에 장애물 배치 및 아이템 추가하였고, ScoreItem점수를 100점에서 1점으로 프리펩화하여 수정하였습니다.
> [Fix] Scene수정 및 ScoreItem점수 조정

- Assets/LHJ/StageScene.unity
일부 벽에서 플레이어가 끼어서 못움직이는 현상이 있어서 일부 벽 크기를 수정하여서 Scene 구현 완료했습니다.
> [Fix] Scene 수정

- Assets/KMS/SCENES/Stage2Scene.unity
> [Fix] 스테이지 씬 수정
